config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  post 'logout', to: 'sessions#destroy'
  resources :chals do
    resources :hits
    member do
      post 'like'
    end
  end
  resources :treats do
    resources :reps
    member do
      post 'like'
    end
  end
  resources :arts do
    resources :coms
    member do
      post 'like'
    end
  end
  resources :tags
  resources :cats do
    resources :arts, only: :index 
    resources :treats, only: :index
    resources :chals, only: :index
  end
  resources :users do
    resources :reps
    resources :hits
    resources :coms
    resources :arts
    resources :treats
    resources :chals
  end

end

app/models/chal.rb
class Chal < ActiveRecord::Base
  belongs_to :user
  belongs_to :cat
  has_many :chaltags
  has_many :challikes, dependent: :destroy
  has_many :tags, :through => :chaltags
  has_many :hits, dependent: :destroy
  validates :cat_id, presence: { message: "must be selected" }
  validates :name, presence: true, length: {minimum: 3, maximum: 50}
  validates :dur, presence: true
  validates :reg, presence: true, length: {minimum: 10, maximum: 3000}
  
  def thumb_up_total
    self.challikes.where(like: true).size
  end
  
  def thumb_dw_total
    self.challikes.where(like: false).size
  end
  
  def comments
    self.hits.where(p_id: 0).size
  end
end

app/controllers/chals_controller.rb
class ChalsController < ApplicationController
  before_action :set_chal, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :edit, :update, :destroy, :like]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /chals
  # GET /chals.json
  def index
    @chals = Chal.all
    if params[:cat_id]
      @cat = Cat.find(params[:cat_id])
      @chals = Chal.all.where(cat_id: @cat.id)
    end
  end

  # GET /chals/1
  # GET /chals/1.json
  def show
    @comms = @chal.hits.where(p_id: '0')
    @reps = @chal.hits
  end

  # GET /chals/new
  def new
    @chal = Chal.new
  end

  # GET /chals/1/edit
  def edit
  end

  # POST /chals
  # POST /chals.json
  def create
    @chal = Chal.new(chal_params)
    @chal.user = current_user
    respond_to do |format|
      if @chal.save
        format.html { redirect_to @chal, notice: 'Chal was successfully created.' }
        format.json { render :show, status: :created, location: @chal }
      else
        format.html { render :new }
        format.json { render json: @chal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chals/1
  # PATCH/PUT /chals/1.json
  def update
    respond_to do |format|
      if @chal.update(chal_params)
        format.html { redirect_to @chal, notice: 'Chal was successfully updated.' }
        format.json { render :show, status: :ok, location: @chal }
      else
        format.html { render :edit }
        format.json { render json: @chal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chals/1
  # DELETE /chals/1.json
  def destroy
    @chal.destroy
    respond_to do |format|
      format.html { redirect_to chals_url, notice: 'Chal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def like
    @chal = Chal.find(params[:id])
    like = Challike.create(like: params[:like], user: current_user, chal: @chal)
    if like.valid?
      flash[:success] = "Your selection was successful"
      redirect_to :back
    else
      flash[:danger] = "Your can only like/dislike once per challenge"
      redirect_to :back
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chal
      @chal = Chal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chal_params
      params.require(:chal).permit(:name, :reg, :dur, :user_id, :cat_id, { :tag_ids => [] })
    end
    def require_same_user
			unless current_user == @chal.user or current_user.admin?
				flash[:danger] = "You can only edit your delete your own articles"
				redirect_to chals_path
			end
    end
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/helpers/chals_helper.rb
module ChalsHelper
end

app/views/chals/_form.html.erb
<div class = "modal-dialog">
	<div class = "modal-content">
    <div class="modal-header" style="padding:35px 50px;">
      <h1><%= (@chal.new_record? ? "Create challenge" : "Update challenge") %></h1>
    </div>
    <div class="modal-body" style="padding:40px 50px;">
      <%= form_for(@chal) do |f| %>
        <% if @chal.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@chal.errors.count, "error") %> prohibited this chal from being saved:</h2>
            <ul>
            <% @chal.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name, :class=>"form-control" %>
        </div>
        <div class="field">
          <%= f.label :reg %><br>
          <%= f.text_area :reg, :class=>"form-control" %>
        </div>
        <div class="field">
          <%= f.label :dur %><br>
          <%= f.number_field :dur, :class=>"form-control" %>
        </div>
        <div class="form-group field">
          <%= collection_select(:chal, :cat_id, Cat.all, :id, :name, {prompt: true}, {class: "form-control"}) %>
        </div>
        <div class="form-group field">
          <%= f.label :tags %><br>
          <%= collection_check_boxes(:chal, :tag_ids, Tag.all, :id, :name, {}, {class: "checkbox-inline"}) %>
        </div>
        <div class="actions">
          <%= f.submit(@chal.new_record? ? "Create challenge" : "Update challenge", :class => 'btn btn-success btn-block') %>
        </div>
      <% end %>
    </div>
    <div class="modal-footer">
      <%= link_to 'Back' ,chals_path, :class=>"btn btn-danger btn-default pull-left" %>
	    <%= link_to "Show" ,@chal, :class=>"btn btn-danger btn-default pull-left" %>
    </div>
  </div>
</div>

app/views/chals/edit.html.erb
<%= render 'form' %>

app/views/chals/index.html.erb
<div class="col-md-12">
  <div class="col-md-12 pathLocation custom_margin">
    <div class = "location_name">
      LISTING CHALLENGES
    </div>
    <% if logged_in? %>
      <%= link_to new_chal_path do %>
        <div class = "add_link add_hover">
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add challenge
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class = "col-md-8">

<!-- For each challenge draw the following-->
<% @chals.each do |chal| %>
  
  	<div class = "treat_css custom_margin add_shadow_border" style="overflow: none;">
  	  
<!-- Treat symtom -->
  		<div class = "index_treat_text">
  		  
  		  <!-- If logged in with author or admin show Edit & Remove button -->
  		  <div class = "edit_delete_control">
          <% if logged_in? && (current_user == chal.user || current_user.admin?) %>
            <%= link_to edit_chal_path(chal) do %>
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            <% end %>
            <%= link_to chal, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            <% end %>
          <% end %>
        </div>
        
        <!-- Treat title -->
        <%= link_to chal do %>
  			  <div class = "how_i"> Let's treat </div> <div class = "index_treat_title"> <b><%= chal.name %></b> </div>
  			<% end %>
  			
  			<!-- Treat Symptom -->
  			<div class = "index_treat_desc">
  			  <%= chal.reg.split[0...30].join(' ')+" ... " %>
        </div>
  		</div>
  		
  			
<!-- Article Controls -->
  
    	<div class = "index_treat_controls" style = "margin-bottom: 15px;">
    	  
  		  <div class = "positive">
          <%= (chal.dur).to_s %> day(s) 
  		  </div>
    		
    		<%= link_to chal.cat do %>
    			<div class = "tag_treat add_hover">
    			  <b><%= chal.cat.name %></b>
    			</div>
    		<% end %>
    		
    		<div class = "author_treat">
    			by <b> <%= chal.user.username %> </b>
    	  </div>
    	  
    	  <div class = "when_treat"> <%= chal.created_at.to_formatted_s(:short) %> </div>
    
    		<div class = "comments_treat"> <span class="glyphicon glyphicon-comment" aria-hidden="true"></span> <%= chal.comments %></span> </div>
    
    		<%= link_to like_treat_path(chal, like: true), method: :post do %>
    			<div class = "like_treat add_hover">
              <i class="glyphicon glyphicon-thumbs-up"></i>
            <%= chal.thumb_up_total %> 
          </div>
        <% end %>
        <%= link_to like_treat_path(chal, like: false), method: :post do %>
    			<div class = "dislike_treat add_hover">
              <i class="glyphicon glyphicon-thumbs-down"></i>
            <%= chal.thumb_dw_total %>
    			</div>
    		<% end %>
    		
    	</div>
  	</div>
 

<% end %>

</div>

 <!-- Ads Placeholder (replace later with dynamic not on each page)-->
<div class = "col-md-4">

    <div class = "add_1 ">
      PLACE HOLDER
    </div>
    <div class = "add_3 ">
      PLACE HOLDER
    </div>
    <div class = "add_2 ">
      PLACE HOLDER
    </div>

</div>
 

app/views/chals/new.html.erb
<%= render 'form' %>

app/views/chals/show.html.erb
<div class = "col-md-8">

<!-- Article Controls -->
  
	<div class = "index_treat_controls" style = "margin-bottom: 15px;">
	  
	  <div class = "positive">
      <%= (@chal.dur).to_s %> day(s) 
  	</div>
		
		<%= link_to @chal.cat do %>
			<div class = "tag_treat add_hover">
			  <b><%= @chal.cat.name %></b>
			</div>
		<% end %>
		
		<div class = "author_treat">
			by <b> <%= @chal.user.username %> </b>
	  </div>
	  
	  <div class = "when_treat"> <%= @chal.created_at.to_formatted_s(:short) %> </div>

		<div class = "comments_treat"> <span class="glyphicon glyphicon-comment" aria-hidden="true"></span> <%= @chal.comments %></span> </div>

		<%= link_to like_chal_path(@chal, like: true), method: :post do %>
			<div class = "like_treat add_hover">
          <i class="glyphicon glyphicon-thumbs-up"></i>
        <%= @chal.thumb_up_total %> 
      </div>
    <% end %>
    <%= link_to like_chal_path(@chal, like: false), method: :post do %>
			<div class = "dislike_treat add_hover">
          <i class="glyphicon glyphicon-thumbs-down"></i>
        <%= @chal.thumb_dw_total %>
			</div>
		<% end %>
		
	</div>
    	  
  <!-- Treat symtom -->
  <div class = "row">
  	<div class = " col-md-12">
  
        <!-- Treat title -->
        <div class = "show_treat_title">
    		  <div class = "how_i" style = "width: 85px;">How I treat</div> <div class = "index_treat_title"><b><%= @chal.name %></b></div>
    		</div>
    		<!-- Treat Symptom -->
    		<div class = "show_treat_sym">
    		  <%= @chal.reg %>
        </div>
  	</div>
  </div>
  
 <div class = "comments_label">
    COMMENTS
  </div>
  
  <!-- Add comment section -->
  <% if logged_in? %>
    <div class = "tmp_relative"> <!-- For relative position of the add button -->
      <%= form_for([@chal, @chal.hits.build]) do |f| %>
        <div class="">
          <%= f.hidden_field :p_id, :value => 0 %>
          <div class = "your_comment">
            <label for="comment">YOUR COMMENT</label>
          </div>
          <div class="">
            <%= f.text_area :text, :class => "form-control text_area_css", :rows => "3", :cols => "30" %>
          </div>
        </div>
        <div class="">
        </div>
          <%= f.submit "ADD COMMENT", :class => "btn add_comment_button add_hover" %>
      <% end %>
    </div>
  <% end %>
  <!-- End of Add comment section -->
     
  <div class="comment_section">
    <div class="post-comments">
      <div class="row">
        
      <!-- Comment in media -->
        
      <% @comms.each do |com| #@art.coms.each do |com| %>
      
        <!-- Each Comment -->
        <div class="media">
          
          <!-- Colapse for comment -->
          <div class="media-heading">
            <button class="btn btn-default btn-xs collapse_btn" type="button" data-toggle="collapse" data-target="#collapse<%= com.id %>" aria-expanded="false" aria-controls="collapseExample">
              <span class="glyphicon glyphicon-minus glyphicon-xs" aria-hidden="true"></span>
            </button> 
            <div class="com_author">
              <%= com.user.username %>
            </div>
            <div class = "com_date">
              <%= time_ago_in_words(com.created_at) %> ago 
            </div>                
            
              <% if logged_in? && (current_user == com.user || current_user.admin?) %>
                <%= link_to [com.chal, com], method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <span class="glyphicon glyphicon-remove pull-right tmp_fx" aria-hidden="true"></span>
                <% end %>
              <% end %>
          </div>
          
          </br>
  
          <!-- Colapse everything from here down -->
          <div class="panel-collapse collapse in" id="collapse<%= com.id %>">
  
            <!-- Actual comment  -->
            <div class="media-body">
              <p><%= com.text %></p>
              
              <% if logged_in? %>
              <!-- Reply form for comm ID -->
              <div class="comment-meta">
                <span>
                  <a class="" role="button" data-toggle="collapse" href="#reply<%= com.id %>" aria-expanded="false" aria-controls="collapseExample">Reply</a>
                </span>
                <!-- Add reply section -->
                <div class = "tmp_relative collapse" id="reply<%= com.id %>"> <!-- For relative position of the add button -->
                  <%= form_for([@chal, @chal.hits.build]) do |f| %>
                      <%= f.hidden_field :p_id, :value => com.id %>
                      <div class = "your_comment">
                        <label for="comment">YOUR COMMENT</label>
                      </div>
                      
                      <%= f.text_area :text, :class => "form-control text_area_css", :rows => "3", :cols => "30" %>
                    
                      <%= f.submit "ADD REPLY", :class => "btn add_comment_button add_hover" %>
                  <% end %>
                </div>
                <!-- End of Add reply section -->
                
              </div>
              <!-- End of reply form -->
              <% end %>
              
              <!-- All replays for comm ID -->
              <% @reps.each do |rep| #@art.reps.each do |rep| %>
                <% if rep.p_id == com.id%>
                  <div class="media" style = "margin-left: 15px; border-left: 1px silver;">
                    
                    <!-- Colapse reply -->
                    <div class="media-heading">
                      <button class="btn btn-default btn-collapse btn-xs collapse_btn" type="button" data-toggle="collapse" data-target="#collapseReply<%= rep.id %>" aria-expanded="false" aria-controls="collapseExample">
                        <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
                      </button> 
                      <div class="com_author">
                        <%= rep.user.username %>
                      </div> 
                      <div class = "com_date">
                        <%= time_ago_in_words(rep.created_at) %> ago
                      </div>
                      
                      <% if logged_in? && (current_user == com.user || current_user.admin?) %>
                        <%= link_to [rep.chal, rep], method: :delete, data: { confirm: 'Are you sure?' } do %>
                          <span class="glyphicon glyphicon-remove pull-right" aria-hidden="true"></span>
                        <% end %>
                      <% end %>
                      
                    </div>
                    
                    </br>
      
                    <div class="panel-collapse collapse in" id="collapseReply<%= rep.id %>">
    
                      <div class="media-body">
                        <p><%= rep.text %></p>
                      </div>
                      
                    </div>
                  </div>
                <% end %>
              <% end %>
              <!-- End of replys -->
              
            </div>
          </div>
        </div>
        <% end %>
        <!-- End of Comment -->
  
      <!-- End of Comment Template -->
      </div>
    </div>
  </div>


</div>  			


 <!-- Ads Placeholder (replace later with dynamic not on each page)-->
<div class = "col-md-4">

    <div class = "add_1 ">
      PLACE HOLDER
    </div>
    <div class = "add_3 ">
      PLACE HOLDER
    </div>
    <div class = "add_2 ">
      PLACE HOLDER
    </div>

</div>