config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  post 'logout', to: 'sessions#destroy'
  resources :chals do
    resources :hits
    member do
      post 'like'
    end
  end
  resources :treats do
    resources :reps
    member do
      post 'like'
    end
  end
  resources :arts do
    resources :coms
    member do
      post 'like'
    end
  end
  resources :tags
  resources :cats do
    resources :arts, only: :index 
    resources :treats, only: :index
    resources :chals, only: :index
  end
  resources :users do
    resources :reps
    resources :hits
    resources :coms
    resources :arts
    resources :treats
    resources :chals
  end

end

app/models/rep.rb
class Rep < ActiveRecord::Base
  belongs_to :user
  belongs_to :treat
  has_many :rep, foreign_key: "p_id", dependent: :destroy
  validates :text, presence: true, length: {minimum: 3, maximum: 50}
end

app/controllers/reps_controller.rb
class RepsController < ApplicationController
  before_action :set_rep, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :edit, :create, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /reps
  # GET /reps.json
  def index
    @reps = Rep.all
  end

  # GET /reps/1
  # GET /reps/1.json
  def show
  end

  # GET /reps/new
  def new
    @rep = Rep.new
  end

  # GET /reps/1/edit
  def edit
  end

  # POST /reps
  # POST /reps.json
  def create
    @treat = Treat.find(params[:treat_id])
    @rep = Rep.new(rep_params)
    @rep.user = current_user
    @rep.treat = @treat
    respond_to do |format|
      if @rep.save
        format.html { redirect_to @treat, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @rep }
      else
        format.html { redirect_to @treat, :flash => { :danger => "Text must not be blank" } }
        format.json { render json: @rep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reps/1
  # PATCH/PUT /reps/1.json
  def update
    respond_to do |format|
      if @rep.update(rep_params)
        format.html { redirect_to @treat, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @rep }
      else
        format.html { render :edit }
        format.json { render json: @rep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reps/1
  # DELETE /reps/1.json
  def destroy
    @rep.destroy
    respond_to do |format|
      format.html { redirect_to @treat, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rep
      @rep = Rep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rep_params
      params.require(:rep).permit(:text, :user_id, :treat_id, :p_id)
    end
    def require_same_user
      @treat = Treat.find(params[:treat_id])
			unless current_user == @treat.user or current_user.admin?
				flash[:danger] = "You can only edit your delete your own articles"
				redirect_to treats_path
			end
    end
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/helpers/reps_helper.rb
module RepsHelper
end

app/views/reps/_form.html.erb
<%= form_for(@rep) do |f| %>
  <% if @rep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rep.errors.count, "error") %> prohibited this rep from being saved:</h2>

      <ul>
      <% @rep.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :treat_id %><br>
    <%= f.text_field :treat_id %>
  </div>
  <div class="field">
    <%= f.label :p_id %><br>
    <%= f.number_field :p_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reps/edit.html.erb
<h1>Editing Rep</h1>

<%= render 'form' %>

<%= link_to 'Show', @rep %> |
<%= link_to 'Back', reps_path %>

app/views/reps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reps</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>User</th>
      <th>Treat</th>
      <th>P</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reps.each do |rep| %>
      <tr>
        <td><%= rep.text %></td>
        <td><%= rep.user %></td>
        <td><%= rep.treat %></td>
        <td><%= rep.p_id %></td>
        <td><%= link_to 'Show', rep %></td>
        <td><%= link_to 'Edit', edit_rep_path(rep) %></td>
        <td><%= link_to 'Destroy', rep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rep', new_rep_path %>

app/views/reps/new.html.erb
<h1>New Rep</h1>

<%= render 'form' %>

<%= link_to 'Back', reps_path %>

app/views/reps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @rep.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @rep.user %>
</p>

<p>
  <strong>Treat:</strong>
  <%= @rep.treat %>
</p>

<p>
  <strong>P:</strong>
  <%= @rep.p_id %>
</p>

<%= link_to 'Edit', edit_rep_path(@rep) %> |
<%= link_to 'Back', reps_path %>