config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  post 'logout', to: 'sessions#destroy'
  resources :chals do
    resources :hits
    member do
      post 'like'
    end
  end
  resources :treats do
    resources :reps
    member do
      post 'like'
    end
  end
  resources :arts do
    resources :coms
    member do
      post 'like'
    end
  end
  resources :tags
  resources :cats do
    resources :arts, only: :index 
    resources :treats, only: :index
    resources :chals, only: :index
  end
  resources :users do
    resources :reps
    resources :hits
    resources :coms
    resources :arts
    resources :treats
    resources :chals
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :arts, dependent: :destroy
  has_many :treats, dependent: :destroy
  has_many :coms, dependent: :destroy
  has_many :artlikes, dependent: :destroy
  has_many :treatlikes, dependent: :destroy
  before_save { self.email = email.downcase}
  validates :username, presence: true,
            uniqueness: {case_sensitive: false},
            length: {minimum: 3, maximum: 30}
  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,  length: {minimum: 5, maximum: 30},
            uniqueness: {case_sensitive: false},
            format: {with: VALID_EMAIL_REGEX}
  validates :password, presence: true,  length: {minimum: 5, maximum: 30}
  has_secure_password
  
  # Returns the hash digest of the given string.
  def User.digest(string)
  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  BCrypt::Engine.cost
  BCrypt::Password.create(string, cost: cost)
  end
  # Returns a random token.
  def User.new_token
  SecureRandom.urlsafe_base64
  end
  # Remembers a user in the database for use in persistent sessions.
  def remember
  remember_token = User.new_token
  update_attribute(:remember_digest, User.digest(remember_token))
  end
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
  return false if remember_digest.nil?
  BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  # Forgets a user.
  def forget
  update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: :index
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :already_logged_in_user, only: :new

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :username, :email, :password_digest, :remember_digest, :admin, :moderator, :password, :password_confirmation)
    end
    def require_same_user
		  unless current_user == @user or current_user.admin?
		    flash[:danger] = "You can only edit your own account"
		    redirect_to root_path
		  end
    end
		def require_admin
		  if logged_in? and !current_user.admin?
		    flash[:danger] = "Only admin users cand perform that action"
		    redirect_to root_path
		  end
		end
		def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    def already_logged_in_user
      if logged_in?
        flash[:success] = "Already logged in"
        redirect_to root_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<body class = "navbar-inverse">
<div class = "modal-dialog">
	<div class = "modal-content">
		<div class="modal-header" style="padding:35px 50px;">
		<!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
			<h4><span class="glyphicon glyphicon-lock"></span> <%= (@user.new_record? ? "Sign up" : "Edit details" )%></h4>
		</div>
		<div class="modal-body" style="padding:40px 50px;">
		<%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
        </div>
      <% end %>
    <div class="form-group field">
      <span class="glyphicon glyphicon-user"></span>
      <%= f.label :fname, "First name" %><br>
      <%= f.text_field :fname, :class=>"form-control" %>
    </div>
    <div class="form-group field">
      <span class="glyphicon glyphicon-user"></span>
      <%= f.label :lname, "Last name" %><br>
      <%= f.text_field :lname, :class=>"form-control" %>
    </div>
    <div class="form-group field">
      <span class="glyphicon glyphicon-asterisk"></span> 
      <%= f.label :username, "Username" %><br>
      <%= f.text_field :username, :class=>"form-control" %>
    </div>
    <div class="form-group field">
      <span class="glyphicon glyphicon-eye-open"></span> 
      <%= f.label :email, "E-mail" %><br>
      <%= f.text_field :email, :class=>"form-control" %>
    </div>
    <div class="form-group field">
      <span class="glyphicon glyphicon-eye-open"></span> 
      <%= f.label :password, "Password" %><br>
      <%= f.password_field :password, :class=>"form-control" %>
    </div>
    <div class="form-group field">
      <span class="glyphicon glyphicon-eye-close"></span>
      <%= f.label :password_confirmation, "Confirmation" %><br>
      <%= f.password_field :password_confirmation, :class=>"form-control" %>
    </div>
    <div class="actions">
      <%= f.submit(@user.new_record? ? "Sign up" : "Update account", :class => 'btn btn-success btn-block') %>
    </div>
    <% end %>
    </div>
		<div class="modal-footer">
		  <%= link_to 'Cancel' ,root_path, :class=>"btn btn-danger btn-default pull-left" %>
		  <p>Already a member? <%= link_to "Log In", login_path %></p>
		</div>
		</div>
	</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Username</th>
      <th>Email</th>
      <% if current_user.try(:admin?) && logged_in? %>
      <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <% if current_user.try(:admin?) && logged_in? %>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>