config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  post 'logout', to: 'sessions#destroy'
  resources :chals do
    resources :hits
    member do
      post 'like'
    end
  end
  resources :treats do
    resources :reps
    member do
      post 'like'
    end
  end
  resources :arts do
    resources :coms
    member do
      post 'like'
    end
  end
  resources :tags
  resources :cats do
    resources :arts, only: :index 
    resources :treats, only: :index
    resources :chals, only: :index
  end
  resources :users do
    resources :reps
    resources :hits
    resources :coms
    resources :arts
    resources :treats
    resources :chals
  end

end

app/models/art.rb
class Art < ActiveRecord::Base
  belongs_to :user
  belongs_to :cat
  has_many :artlikes, dependent: :destroy
  has_many :arttags, :foreign_key => "art_id", dependent: :destroy
  has_many :tags, :through => :arttags
  has_many :coms, dependent: :destroy
  validates :cat_id, presence: { message: "must be selected" }
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 3000}
  
  def thumb_up_total
    self.artlikes.where(like: true).size
  end
  
  def thumb_dw_total
    self.artlikes.where(like: false).size
  end
  
  def comments
    self.coms.where(p_id: 0).size
  end
  
  def tags
    self.tag_ids
  end
  
end

app/models/artlike.rb
class Artlike < ActiveRecord::Base
  belongs_to :user
  belongs_to :art
  validates :user_id, presence: { message: "You must be logged in!" }
  validates_uniqueness_of :user, scope: :art
end

app/models/arttag.rb
class Arttag < ActiveRecord::Base
  belongs_to :art
  belongs_to :tag
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  has_many :arts, dependent: :destroy
end

app/models/chal.rb
class Chal < ActiveRecord::Base
  belongs_to :user
  belongs_to :cat
  has_many :chaltags
  has_many :challikes, dependent: :destroy
  has_many :tags, :through => :chaltags
  has_many :hits, dependent: :destroy
  validates :cat_id, presence: { message: "must be selected" }
  validates :name, presence: true, length: {minimum: 3, maximum: 50}
  validates :dur, presence: true
  validates :reg, presence: true, length: {minimum: 10, maximum: 3000}
  
  def thumb_up_total
    self.challikes.where(like: true).size
  end
  
  def thumb_dw_total
    self.challikes.where(like: false).size
  end
  
  def comments
    self.hits.where(p_id: 0).size
  end
end

app/models/challike.rb
class Challike < ActiveRecord::Base
  belongs_to :user
  belongs_to :chal
  validates :user_id, presence: { message: "You must be logged in!" }
  validates_uniqueness_of :user, scope: :chal
end

app/models/chaltag.rb
class Chaltag < ActiveRecord::Base
  belongs_to :chal
  belongs_to :tag
end

app/models/com.rb
class Com < ActiveRecord::Base
  belongs_to :user
  belongs_to :art
  has_many :com, foreign_key: "p_id", dependent: :destroy
  validates :text, presence: true, length: {minimum: 3, maximum: 30}
end

app/models/hit.rb
class Hit < ActiveRecord::Base
  belongs_to :user
  belongs_to :chal
  has_many :hit, foreign_key: "p_id", dependent: :destroy
  validates :text, presence: true, length: {minimum: 3, maximum: 50}
end

app/models/rep.rb
class Rep < ActiveRecord::Base
  belongs_to :user
  belongs_to :treat
  has_many :rep, foreign_key: "p_id", dependent: :destroy
  validates :text, presence: true, length: {minimum: 3, maximum: 50}
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :arttags, :foreign_key => "tag_id", dependent: :destroy
  has_many :arts, :through => :arttags
end

app/models/treat.rb
class Treat < ActiveRecord::Base
  belongs_to :user
  belongs_to :cat
  has_many :treattags
  has_many :treatlikes, dependent: :destroy
  has_many :tags, :through => :treattags
  has_many :reps, dependent: :destroy
  validates :cat_id, presence: { message: "must be selected" }
  validates :name, presence: true, length: {minimum: 3, maximum: 50}
  validates :sym, presence: true, length: {minimum: 10, maximum: 3000}
  validates :reg, presence: true, length: {minimum: 10, maximum: 3000}
  
  def thumb_up_total
    self.treatlikes.where(like: true).size
  end
  
  def thumb_dw_total
    self.treatlikes.where(like: false).size
  end
  
  def comments
    self.reps.where(p_id: 0).size
  end
end

app/models/treatlike.rb
class Treatlike < ActiveRecord::Base
  belongs_to :user
  belongs_to :treat
  validates :user_id, presence: { message: "You must be logged in!" }
  validates_uniqueness_of :user, scope: :treat
end

app/models/treattag.rb
class Treattag < ActiveRecord::Base
  belongs_to :treat
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :arts, dependent: :destroy
  has_many :treats, dependent: :destroy
  has_many :coms, dependent: :destroy
  has_many :artlikes, dependent: :destroy
  has_many :treatlikes, dependent: :destroy
  before_save { self.email = email.downcase}
  validates :username, presence: true,
            uniqueness: {case_sensitive: false},
            length: {minimum: 3, maximum: 30}
  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,  length: {minimum: 5, maximum: 30},
            uniqueness: {case_sensitive: false},
            format: {with: VALID_EMAIL_REGEX}
  validates :password, presence: true,  length: {minimum: 5, maximum: 30}
  has_secure_password
  
  # Returns the hash digest of the given string.
  def User.digest(string)
  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  BCrypt::Engine.cost
  BCrypt::Password.create(string, cost: cost)
  end
  # Returns a random token.
  def User.new_token
  SecureRandom.urlsafe_base64
  end
  # Remembers a user in the database for use in persistent sessions.
  def remember
  remember_token = User.new_token
  update_attribute(:remember_digest, User.digest(remember_token))
  end
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
  return false if remember_digest.nil?
  BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  # Forgets a user.
  def forget
  update_attribute(:remember_digest, nil)
  end
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/coms_helper.rb
module ComsHelper
end

app/helpers/hits_helper.rb
module HitsHelper
end

app/helpers/reps_helper.rb
module RepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreenLife</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    
  <% bgg = image_path("bg.jpg") %>
  
  <style>
  body {
  	margin: 0;
  	padding-top: 95px; 
  	
  	/*background-color: white;*/
  	
  	background-color: #e7e7e7;
  	background: url(<%= bgg %>);
  	
  }
  </style>
  
</head>
<nav>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class = "container">
      <!-- BUTTON that appears when window is resized small -->
      <button class="navbar-toggle" data-toggle = "collapse" data-target=".navHeaderCollapse">
        <span class = "icon-bar"></span>
        <span class = "icon-bar"></span>
        <span class = "icon-bar"></span>
      </button>
      <!-- MENU / LOGIN -->
      <div class = "collapse navbar-collapse navHeaderCollapse">
			<ul class="nav navbar-nav navbar-right">
        <li> 
          <% if logged_in? %>
            <section>Welcome <%= current_user.username %>, <%= link_to 'Log out', logout_path, method: :destroy %></section>
          <% else %>
          <section>Welcome Guest, <%= link_to "Log In", login_path%> / <%= link_to "Sign up", signup_path%></section>
          <% end %>
        </li>
			</ul>	
		</div>		
		<!-- MENU / NAVGATION -->
		<div class = "collapse navbar-collapse navHeaderCollapse">
		  <%= image_tag "logo.png", :class => 'navbar-brand' %>
			<ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home' ,root_path %></li>
        <li><%= link_to 'Articles',arts_path %></li>
        <li><%= link_to 'Hawaii Treats',treats_path %></li>
        <li><%= link_to 'Challenges',chals_path %></li>
        <% if current_user.try(:admin?) && logged_in?  %>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Categories", cats_path %></li>
        <li><%= link_to "Tags", tags_path %></li>
        <% end %>
				<!-- SEARCH BUTTON (implement functionality) -->
				<li class = "dropdown">
					<a href = "#" class = "dropdown-toggle" data-toggle = "dropdown"> <span class="glyphicon glyphicon-search"></span></a>
					<ul class = "dropdown-menu">
						<li><a href="#"><input type="text" style="width: auto;" class="form-control" id="search"></a></li>
					</ul>
				</li>
			 </ul>	
		  </div>
	  </div>   
  </div>
</nav>
<body>
  
<div id="wrap">
  	<div class="container clearfix" style="" id="main">
  		<% flash.each do |key, value| %>
  			<div class="alert alert-<%= key %>"><%= value %></div>
  		<% end %>
  		<%= yield %>
  	</div>
</div>	
	
  <div class = "bottomFooter" id="footer">
    <div class = "container" >
      
        <div style="background-color: red; height: 75px; background-color: #4e4e4e;">
        </div>
      
    </div>
  </div>

  

  
</body>
</html>